### ISSUE TITLE
Tag editing is not currently modal

### ISSUE THREAD

**Issue by artisologic** [artisologic/github-stars-organiser#4]
There is potential for confusion if the user just blurs out for example.

**Comment by artisologic** [comment]
Hey @peduarte, what do you think is the best way to do this?

Currently:
* Pressing enter in the field exits edit mode and saves
* Pressing escape in the field exits edit mode but restore old values

Basically I don't want the user to end up in a situation where they start editing some tags, but then blur out and forget to exit edit mode for that one, opening another one then for example.

Initially I was thinking to apply a "modal" behaviour to the input field once in edit mode.
Basically it would stop all events anywhere else on the page, etc
So you'd have to press "enter" to validate or "esc" to cancel, or if you clicked outside, it'd be the same as "esc".

Could potentially be a bit annoying though as it's not like a proper modal window where you see something on top. Maybe I don't need to stop all events.

In which case, I could do this:

* Scenario 1:
  * Pressing enter in the field exits edit mode and saves
  * Pressing escape in the field exits edit mode but restore old values
  * Leaving the field exits edit mode but restore old values

* Scenario 2:
  * Pressing enter in the field exits edit mode and saves
  * Pressing escape in the field exits edit mode but restore old values
  * Leaving the field exits edit mode and saves

Interested to get your take on this when you have a minute.

Cheers!

**Comment by peduarte** [comment]
Yeah, that's an interesting one.
I think for MVP sake, Scenario 1 more appropriate.
This way, it only saves if the user actually initiates the action (pressing enter)


However, if you want to avoid cases where the user doesn't know what's going on you could implement something very similar to the way you can rename your Repository's description and URL.

Here's how they do it:

<img width="804" alt="screenshot 2015-09-11 10 24 33" src="https://cloud.githubusercontent.com/assets/372831/9811461/5644ec56-586f-11e5-9036-1446d357ddcd.png">

And when you click on Edit, it shows this:
<img width="809" alt="screenshot 2015-09-11 10 25 07" src="https://cloud.githubusercontent.com/assets/372831/9811471/6768ae3c-586f-11e5-82d3-5a8c21e01ed1.png">

Pressing Escape doesn't do anything
Pressing Enter saves

**Comment by artisologic** [comment]
See, the way they do it for the description is kinda what I'm trying to avoid.
Although yes it is more explicit that you are in a "mode" because you have the save and cancel buttons but I still don't really like things like that when you can start something but then go on with your life, scroll down, do other things and it's still in that "state".

**Comment by peduarte** [comment]
Yeah that's true... I think for simplicity, Scenario 1 is good enough.

**Comment by artisologic** [comment]
Yeah I'm just wondering if the blur -> cancel might be a bit annoying.
I guess if it was blur -> save, we're not dealing with very complicated stuff so you could always re-edit.

I'm torn...

**Comment by peduarte** [comment]
Personally, I think it's better to only save on Enter....

**Comment by artisologic** [comment]
Ok, I'll go with that one and we'll see how it feels.
Cheers @peduarte!

**Comment by peduarte** [comment]
👍
